### PR TITLE
Fixed Inability to uninstall ZZZ + Update to README.md for ZZZ

### PR DESCRIPTION
**Pull request by NSPC911**
# Main Goal
- Fixes Collapse's inability to uninstall Zenless Zone Zero
   Yeah, it is literally 1 line lmao but I'm bored so `¯\_(ツ)_/¯`
- Updates README.md for Zenless Zone Zero's features

Issue screenshot:

image

## PR Status :
- Overall Status: Done
- Commits: Done
- Synced to base (Collapse: main): Yes
- Build status: OK
- Crashing: Yes
- Bug found caused by PR: #511 

### Templates

<details>
  <summary>Changelog Prefixes</summary>
  mb what are these for?
  ```
    **[New]**
    **[Imp]**
    **[Fix]**
    **[Loc]**
    **[Doc]**
  ```

</details>

### CODE REVIEW

**Comment by NSPC911** [comment]
I could also update the README.md for ZZZ's capabilities in Collapse

**Comment by Cryotechnic** [comment]
> I could also update the README.md for ZZZ's capabilities in Collapse

If you want to, go ahead!

**Comment by NSPC911** [comment]
@Cryotechnic done

**Review by bagusnl — APPROVED** [review]

**Comment by bagusnl** [comment]
Approved and merged! Thanks for the contribution~

**Pull request merged**
