### PR TITLE
Bilibili Region Support

### PR DESCRIPTION
**Pull request by bagusnl**
[Build-Canary](https://github.com/CollapseLauncher/Collapse/actions/workflows/build.yml)
#279 

Checklist
- [x] Metadata preparation
- [x] Initialize SDK key in ResourceURL
- [x] Prepare INI defaults for Bilibili (cps=bilibili, channel=14, sub_channel=0)
- [x] Download SDK on install (note: for some reason in GI, both size and pkg_size returns 0)
- [x] Check SDK on repair (sdk_pkg_version for GI and HSR (inside the zip))
- [ ] Code checks

### CODE REVIEW

**Review by bagusnl — COMMENTED** [review]
LGTM

**Review by neon-nyan — APPROVED** [review]
LGTM too!

**Review by muscularcandy67 — APPROVED** [review]
LGTM

**Review by Cryotechnic — APPROVED** [review]
Great work, LGTM!

**Pull request merged**
