### PR TITLE
Implement SimpleDialog for Force Updating in Metered Connection

### PR DESCRIPTION
**Pull request by DeepChirp**
Updated for Simplified Chinese

### CODE REVIEW

**Comment by bagusnl** [comment]
For language resouce we usually use transifex as detailed here #146 (new string will get synced when branch is merged to main)

While submitting the translation in PR is all good, I just want to confirm first as you wont get credited in the Transifex dashboard

**Comment by DeepChirp** [comment]
> For language resouce we usually use transifex as detailed here #146 (new string will get synced when branch is merged to main)
> 
> While submitting the translation in PR is all good, I just want to confirm first as you wont get credited in the Transifex dashboard

Oh, it doesn't matter, just that the strings are localized.

**Comment by bagusnl** [comment]
Alrighty, I'd assume the same thing goes for the #288

Will check the commits for both PRs and merge when ready

**Review by bagusnl — APPROVED** [review]
All looks good, merging.

Thank you for the help in localizing Collapse!

**Pull request merged**
